sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tJ3aT99J1gG9J3MVT3M
    access-key-secret: NBF9YPg8ywsTktRbNbOu2Cpui8dNRs
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: tkzc00-sky-take-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0